variable "public_key" {
  type = string
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCF7Ekxi/95rph551v53kXQA/i+8Pc2e7MocCJladEEuf//UsmgmV2Q86FIKnEF4vsm0N09WHEn4xbQXLzk1Kb7EJZkSLyPdoOuemh4QNRC/XaH5aiYQlgH5j5gdY4x8wtEnomUjYBV6UFgRSpamgoDatARUufwGpFTmZR2uC+FdstNscmu1RwRZBNckpQPB3BsTOs1ryW5Sy+PsuTsheKNLEsKkr7mXXrC01ZtEpNn/t/rpbK7eYKrc8/sobrYMsaKXTqGy+JFFfeDp+We4M71hX76aj0AP40cg/OXGdDLePdDaxP0yz6tb6EBHjFNDCh2xWGzQ3P9zUdmMuoXN8d Generated By Termius"
}

variable "avail_zone" {
  type = string
  default = "us-east-1a"
}

variable "vpc_ep_svc_name" {
  type = string
  default = "com.amazonaws.us-east-1.s3"
}

variable "config-NetworkMiner" {
  default = "NetworkMiner.desktop"
}

variable "config-45-allow-colord" {
  default = "45-allow-colord.sh"
}
